# Generated by Django 3.1.5 on 2021-01-19 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('buttonText', models.TextField(verbose_name='Текст кнопки')),
                ('text', models.TextField(blank=True, verbose_name='Текст под формой')),
                ('img', models.URLField(blank=True, default='', max_length=400, verbose_name='Фоновое изображение')),
                ('background_color', models.CharField(default='#ebebeb', max_length=7, verbose_name='Цвет фона')),
            ],
        ),
        migrations.CreateModel(
            name='BlockHeadingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок страницы')),
                ('description', models.TextField(blank=True, verbose_name='Описание страницы')),
                ('buttonText', models.TextField(verbose_name='Текст кнопки')),
                ('img', models.URLField(blank=True, default='', max_length=400, verbose_name='Фоновое изображение')),
                ('background_color', models.CharField(default='#ebebeb', max_length=7, verbose_name='Цвет фона')),
            ],
        ),
        migrations.CreateModel(
            name='BlockSectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=256, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('img', models.URLField(blank=True, default='', max_length=400, verbose_name='Фоновое изображение')),
                ('background_color', models.CharField(default='#ebebeb', max_length=7, verbose_name='Цвет фона')),
            ],
        ),
        migrations.CreateModel(
            name='BlockTextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('img', models.URLField(blank=True, default='', max_length=400, verbose_name='Фоновое изображение')),
                ('background_color', models.CharField(default='#ebebeb', max_length=7, verbose_name='Цвет фона')),
            ],
        ),
        migrations.CreateModel(
            name='MailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{11}$')])),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
