# Generated by Django 3.1.5 on 2021-01-19 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{11}$')])),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blockformmodel',
            name='img',
            field=models.URLField(blank=True, default='', max_length=400, verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='blockheadingmodel',
            name='img',
            field=models.URLField(blank=True, default='', max_length=400, verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='blocksectionmodel',
            name='img',
            field=models.URLField(blank=True, default='', max_length=400, verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='blocktextmodel',
            name='img',
            field=models.URLField(blank=True, default='', max_length=400, verbose_name='Фоновое изображение'),
        ),
    ]
